name: Simple Runner

on:
  push:
  workflow_dispatch:

jobs:
  run-simple:
    runs-on: ubuntu-latest
    steps:
     - name: Show runner information
       run: |
         echo "OS: $RUNNER_OS"
         echo "Image: $ImageOS"
         echo "Version: $ImageVersion"
     - name: Print GitHub API URL
       run: echo "GitHub API"

