name: Simple Runner

on:
  push:
  workflow_dispatch:

jobs:
  run-simple:
    runs-on: ubuntu-latest
    steps:
     - name: Show runner information
       run: |
         echo "OS: $RUNNER_OS"
         echo "Runner Name: $RUNNER_NAME"
         echo "Image: $ImageOS"
         echo "Version: $ImageVersion"
         echo "Scale Set Info: $ACTIONS_RUNNER_DEBUG"
     - name: Print GitHub API URL
       run: echo "GitHub API"

